{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: python-api-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Use '|' to tell YAML: "Everything indented below this is ONE long string"
    alb.ingress.kubernetes.io/actions.python-api-link-service-to-ingress: |
      {
        "type": "url-rewrite",
        "urlRewriteConfig": {
          "rewrites": [
            {
              "regex": "^/api/(.*)",
              "replace": "/$1"
            }
          ]
        }
      }

spec:
  ingressClassName: alb

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: python-api-link-service-to-ingress
                port:
                  name: use-annotation

{{- end }}
