{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: python-api-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

spec:
  ingressClassName: alb

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix  # <-- CHANGED TO PREFIX
            backend:
              service:
                name: python-api-link-service-to-ingress
                port:
                  number: 80  # <-- CHANGED FROM name: use-annotation TO A NUMERICAL PORT
                  # Note: Replace 80 with your actual Python API target service port if different

{{- end }}
