# Python API Settings
pythonApp:
  replicaCount: 1

# Redis Settings
# Overriding base defaults for the development environment
redis:
  enabled: true
  persistence:
    enabled: true

# Shared/Global Settings
ingress:
  enabled: true
  host: prod.api.test-domain.local
  path: /api  # <-- ADDED THIS LINE
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
